apiVersion: v1
kind: Service
metadata:
  name: scaletestapp-service
  namespace: scaletestapp-namespace
  labels:
    app: scaletestapp
spec:
  selector:
    app: scaletestapp
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort