apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-app-sm
  namespace: scaletestapp-namespace
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: scaletestapp           
  namespaceSelector:
    matchNames:
      - scaletestapp-namespace
  endpoints:
    - interval: 10s
      path: /metrics
      port: http